# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiDocs < Formula
  desc "AI-generated memory files manager for Git"
  homepage "https://github.com/trknhr/ai-docs"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/trknhr/ai-docs/releases/download/v0.0.1/ai-docs_Darwin_x86_64.tar.gz"
      sha256 "ea7dfcde150af8b5a24515ef36e91e8e5be361e6b9cf3e99881c318c50f9bb5d"

      def install
        bin.install "ai-docs"
      end
    end
    on_arm do
      url "https://github.com/trknhr/ai-docs/releases/download/v0.0.1/ai-docs_Darwin_arm64.tar.gz"
      sha256 "9b67dc714a5d60ff222bb95a63e9f9a5727326f0042c8fac0b12f877a6e3281f"

      def install
        bin.install "ai-docs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/trknhr/ai-docs/releases/download/v0.0.1/ai-docs_Linux_x86_64.tar.gz"
        sha256 "866ee9823352a4ed8c18d1e5bb483b39bcd270cc7e2ed9e97544c35b8eba9fc4"

        def install
          bin.install "ai-docs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/trknhr/ai-docs/releases/download/v0.0.1/ai-docs_Linux_arm64.tar.gz"
        sha256 "8e3ffacb6e238fa007b3851ab6a787c4e5453dfb4b5e28c60e6efc455f607a56"

        def install
          bin.install "ai-docs"
        end
      end
    end
  end

  test do
    system "#{bin}/ai-docs", "--version"
  end
end
