# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiu < Formula
  desc "AI Utils - Execute prompts with local AI CLIs"
  homepage "https://github.com/trknhr/ai-utils"
  version "0.3.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.3.4/aiu_0.3.4_darwin_amd64.tar.gz"
      sha256 "5865bd51974d6d17fe0ee010ca90221a2f255190707932b34f67c5dab4172b53"

      def install
        bin.install "aiu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.3.4/aiu_0.3.4_darwin_arm64.tar.gz"
      sha256 "2f5e94e4caa20a7d82eaee08f35aaf31a9fd6721e3a03beda9f3c8dd5898a329"

      def install
        bin.install "aiu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.3.4/aiu_0.3.4_linux_amd64.tar.gz"
      sha256 "02bfeb4934cf869933b1fcf11f6b908cf7e0b1714226a8fdbecc50cce472dcf8"
      def install
        bin.install "aiu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.3.4/aiu_0.3.4_linux_arm64.tar.gz"
      sha256 "08644ef0a6ca97cad493359f0631bcf000125b87543d8b52abad41619076e248"
      def install
        bin.install "aiu"
      end
    end
  end

  test do
    system "#{bin}/aiu", "--help"
  end
end
