# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiu < Formula
  desc "AI Utils - Execute prompts with local AI CLIs"
  homepage "https://github.com/trknhr/ai-utils"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.4.0/aiu_0.4.0_darwin_amd64.tar.gz"
      sha256 "63fb663bdcf916964959a123b142df746f866d47fb1cd31fe02f242fdcdf87a9"

      def install
        bin.install "aiu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.4.0/aiu_0.4.0_darwin_arm64.tar.gz"
      sha256 "d8a5d31eda6d93ce1afff61043b59541e65f0f596287fea10ae6c3a5cec613f9"

      def install
        bin.install "aiu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.4.0/aiu_0.4.0_linux_amd64.tar.gz"
      sha256 "57d6eaeab2f33727d90b3d8ec258eedf18d07ee2cfd6e1de435629c48963d117"
      def install
        bin.install "aiu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.4.0/aiu_0.4.0_linux_arm64.tar.gz"
      sha256 "60cc331b2871f4a6e78249d7b8e9471e90b818e4261be4b2ecfa45b8e328b073"
      def install
        bin.install "aiu"
      end
    end
  end

  test do
    system "#{bin}/aiu", "--help"
  end
end
