# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiu < Formula
  desc "AI Utils - Execute prompts with local AI CLIs"
  homepage "https://github.com/trknhr/ai-utils"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.4.1/aiu_0.4.1_darwin_amd64.tar.gz"
      sha256 "dc5807ad5c0665fcd37bcbd98ac486edac6cd57eae6bc536dba572b1a0a31439"

      def install
        bin.install "aiu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.4.1/aiu_0.4.1_darwin_arm64.tar.gz"
      sha256 "4f340da3de0615d23e315cc40958923f975ccc511a3960ba46b8790d83f11faa"

      def install
        bin.install "aiu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.4.1/aiu_0.4.1_linux_amd64.tar.gz"
      sha256 "1f797081582c443bc09225bc075ae85e699a6c4712fe9665667dad39e5085e63"
      def install
        bin.install "aiu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trknhr/ai-utils/releases/download/v0.4.1/aiu_0.4.1_linux_arm64.tar.gz"
      sha256 "68e55043c227df7ae3c2ef05968952191bf21e9932cef434f54786d0eb0173de"
      def install
        bin.install "aiu"
      end
    end
  end

  test do
    system "#{bin}/aiu", "--help"
  end
end
