# Generated by envvault-release package-manifests. Do not edit by hand.
class Envvault < Formula
  desc "Local-first credential launcher and localhost credential proxy"
  homepage "https://github.com/trknhr/envvault"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/trknhr/envvault/releases/download/v0.1.0/envvault_v0.1.0_darwin_amd64.tar.gz"
      sha256 "a7ace04d3cdadd37aa6f4a4a37f1e285606ee93e6dd24c9cf13e1a017b7fb4a6"
    end
    on_arm do
      url "https://github.com/trknhr/envvault/releases/download/v0.1.0/envvault_v0.1.0_darwin_arm64.tar.gz"
      sha256 "a14ff74a80a0b770afd1f82cbd5834afceffb730c15ade891a4820437eff30a3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/trknhr/envvault/releases/download/v0.1.0/envvault_v0.1.0_linux_amd64.tar.gz"
      sha256 "c7129a0f8ac9b9bf22dfa9456db7655c1eefaf0a068e7116fbd0aef831e90014"
    end
    on_arm do
      url "https://github.com/trknhr/envvault/releases/download/v0.1.0/envvault_v0.1.0_linux_arm64.tar.gz"
      sha256 "e82445a046dfa4eedb8cd859ac1fc3c1f3c4a9ad4a664f835e3bfe4bc29dfd7f"
    end
  end

  def install
    bin.install "envvault"
  end

  test do
    system "#{bin}/envvault", "completion", "bash"
  end
end
