# Generated by envvault-release package-manifests. Do not edit by hand.
class Envvault < Formula
  desc "Run local apps without plaintext .env secrets"
  homepage "https://github.com/trknhr/envvault"
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/trknhr/envvault/releases/download/v0.3.1/envvault_v0.3.1_darwin_amd64.tar.gz"
      sha256 "c1c6a25efe182b86d2c7763261560fb57c017dcfa17f763f671811727853dca7"
    end
    on_arm do
      url "https://github.com/trknhr/envvault/releases/download/v0.3.1/envvault_v0.3.1_darwin_arm64.tar.gz"
      sha256 "9b9c7a13e8c94797e8dd268cc58c2fac7cfc7116bf855867c22cac57ca9d92b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/trknhr/envvault/releases/download/v0.3.1/envvault_v0.3.1_linux_amd64.tar.gz"
      sha256 "5f5cb5cbdf08b1298f0e1424e928d05e69058b41c834e8b327fb5e3acb2fab4a"
    end
    on_arm do
      url "https://github.com/trknhr/envvault/releases/download/v0.3.1/envvault_v0.3.1_linux_arm64.tar.gz"
      sha256 "080a0f23ca201ae54c866e71bf578457d50327d0143cf0e9d934e5ea0a58aeec"
    end
  end

  def install
    bin.install "envvault"
  end

  test do
    system "#{bin}/envvault", "version"
  end
end
